#!/usr/bin/env sh

[ -z "$1" ] && OPT="BEST" || OPT="$1"
OPT=`echo "$OPT" | sed "s/BEST/FAST_MATH BOUNCES=10 SMART_BOUNCES BVH THREADS_Y=4/"`

OPT=`echo "$OPT" | tr " " "\n" | sort | tr "\n" " " | xargs`
echo "Optimizations: $OPT"


cd src
make clean
make DEFINES="$OPT"
cd ..

OUT_DIR="results"
mkdir -p "$OUT_DIR"

nsys profile -f true -o "$OUT_DIR/$OPT.qdstrm" "./src/cudart" "$OUT_DIR/$OPT.ppm" 2>&1 | tee "$OUT_DIR/$OPT.log"
/usr/lib/nsight-systems/host-linux-x64/QdstrmImporter -f -i "$OUT_DIR/$OPT.qdstrm" -o "$OUT_DIR/$OPT.nsys-rep"
rm "$OUT_DIR/$OPT.qdstrm"
